### ISSUE TITLE
Crash when placing Sanguine Psiogenesis Device with Thermal Dynamics installed

### ISSUE THREAD

**Issue by Lgmrszd** [phantamanta44/psi-costs#3]
Steps to reproduce:
1. Have mods from first crashreport installed
2. Get yourself Sanguine Psiogenesis Device
3. Attempt to place it.

Crash report 1: https://gist.github.com/Lgmrszd/c9c2d79cf1d96f3e6d62327cb36c850c
Stacktrace from another crash report (with bunch of other mods and also VanillaFix, showing affected TD methods): https://gist.github.com/Lgmrszd/46fee6edf5bf4f8caf7444dabdbc78bf

**Comment by phantamanta44** [comment]
unfortunately, this is because libnine version 1.2.0 introduced breaking changes in fluid handling; you'll have to drop back to a previous version for now. i'll push a update soon
